language: php
dist: xenial

matrix:
  include:
    - php: '7.2'
      env:
        - USE_PHPSTAN="1"
        - USE_FIXER="1"
    - php: '7.3'
      env:
        - USE_PHPSTAN="1"
        - USE_FIXER="1"
    - php: '7.4'
      env:
        - USE_FIXER="1"
        - USE_PHPSTAN="1"

cache:
  directories:
    - $HOME/.cache/composer/files

install: composer install $COMPOSER_FLAGS

script:
  - vendor/bin/phpunit $PHPUNIT_FLAGS
  - '[[ $USE_FIXER != "1" ]] || vendor/bin/php-cs-fixer fix src/ --dry-run --verbose'
  - '[[ $USE_PHPSTAN != "1" ]] || composer phpstan'

after_script:
  - '[[ $USE_COVERAGE != "1" ]] || ./vendor/bin/php-coveralls --verbose'

branches:
  only:
    - master
